version: "2"  
services:
  jenkins:
    image: index.alauda.cn/alaudaorg/alauda-jenkins:72196a28f182539c2ff6719e6df2a408d63980e8
    ports:
      - 8080:8080
    network_mode: bridge
    restart: always
    user: root
    volumes:
      - /var/lib/jenkins_8080:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
